
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : MonoBehaviour
{
    public static GameManager instance;

    private void Awake()
    {
        if (instance == null)
        {
            instance = this;
            DontDestroyOnLoad(gameObject);
        }
        else
        {
            Destroy(gameObject);
        }    
    }

    public void LoadNivel()
    {
        Debug.Log("Loading level...");
        SceneManager.LoadScene("Nivel_1");   // Load the level here

        Debug.Log("Level loaded successfully.");
        // For example, using SceneManager.LoadScene("LevelName");
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
